name: Case sensitivity test

on:
  workflow_dispatch:
    inputs:
      system:
        description: "Select a system to build on"
        required: true
        type: choice
        options:
          - gadi
          - setonix
      build_branch:
        description: "Select a firedrake branch to build"
        required: true
        type: string

jobs:
  build:
    env:
      USER: ${{ secrets[format('{0}_USER', inputs.system)] }}
      SSHKEY: ${{ secrets[format('{0}_TESTING_KEY',inputs.system)] }}
      HOSTKEY: ${{ secrets[format('{0}_HOST_KEY',inputs.system)] }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        with:
          system: ${{ inputs.system }}
      - name: Try ssh
        shell: bash
        run: |
          ssh ${{ inputs.system }} '/bin/echo "hello there" > ~/my_test_file.txt'
      - name: Whats your problem?
        if: ${{ inputs.build_branch != 'master' && inputs.build_branch != 'release' }}
        run: |
          echo ${{ inputs.build_branch }}" Hi?"