name: Run regression tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload run log
        uses: actions/upload-artifact@v4
        with:
          name: run-log
          path: tsp_db.sqlite3